[build.environment]
GO_VERSION = "1.26.3"
HUGO_VERSION = "0.164.0"
NODE_VERSION = "18.19.1"
TZ = "America/New_York"

[build]
publish = "public"
command = """\
  git config --global core.quotepath false && \
  hugo build --gc --minify --baseURL "${URL}"
  """
